---
title: "Homework1 Maps"
output: html_document
date: "2025-10-01"
---

```{r}
rm(list = ls())

southAmericaLink="https://github.com/DACSS690D-SpatialAnalysis/Homework1/raw/refs/heads/main/southAmerica_32721.gpkg"

#create temporary file path on computer
#.gpkg extension for geopackage
temp_file <- tempfile(fileext = ".gpkg")

#download the file from the URL 
download.file(southAmericaLink, temp_file, mode = "wb")

library(sf)

st_layers(temp_file)    #st_layers shows whats inside the gpkg file 

southAmerica <- st_read(temp_file)  
```


```{r}
southAmerica <- st_read(southAmericaLink, layer = "continent")
southAmMobiles_ddm <- st_read(southAmericaLink, layer = "mobiles_ddm")
southAmMobiles_psm <- st_read(southAmericaLink, layer = "mobiles_psm")

```

```{r}
st_crs(southAmerica)$epsg
```

```{r}
library(ggplot2)
library(scales)

ggplot() + theme_light() +
  geom_sf(data = southAmerica) + 
  coord_sf(datum = st_crs(southAmerica)) + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") 
```

```{r}
plot1_a=ggplot() + theme_light() +
  #base
  geom_sf(data = southAmerica,fill="white",color="grey80") +
  # layer
  geom_sf(data=southAmMobiles_ddm,
          alpha=0.5,
          shape=20,
          size=0.7,
          color="red")+
  coord_sf(datum = st_crs(southAmerica)) + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") 

plot1_a
```

```{r}
library(leaflet)
# needs geographic CRS
ddm_4326 <- st_transform(southAmMobiles_ddm, crs = 4326)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  # names in english
  addCircleMarkers(data = ddm_4326,
                   color="red",
                   stroke=0,
                   radius = 1.5,
                   opacity = 0.1)
```

```{r}
interactive_ddm=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  # names in english
  addCircleMarkers(data = ddm_4326,
                   color="red",
                   stroke=0,
                   radius = 1.5,
                   opacity = 0.1)
interactive_ddm
```


# static PSM

```{r}

library(dplyr)

southAmMobiles_psm <- southAmMobiles_psm |> 
  mutate(mobiles = southAmerica$mobiles)

static_psm=ggplot() + theme_light() +
  #base
  geom_sf(data = southAmerica,fill="white",color="grey80") +
  # layer
  geom_sf(data=southAmMobiles_psm,
          shape=20,
          aes(size=mobiles/5000,color=factor(mobiles_outlier)))+
  scale_size_area(
    name = "Mobiles (x5,000)", # Name for the legend
    max_size = 15) +       
  guides(color="none") + 
  
  coord_sf(datum = st_crs(southAmerica)) + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") 

static_psm
```
## interactive PSM 

```{r}
# CRS for leaflet
psm_4326 <- st_transform(southAmMobiles_psm, crs = 4326)


interactive_psm=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = psm_4326,
                   fillColor = "blue",
                   stroke = T, #border
                   color="white", #border color
                   fillOpacity = 0.4,
                   label = ~Country,
                   radius = ~size)
interactive_psm
```

## static CHORO

```{r}
static_choro=ggplot() + theme_light() +
  #base
  geom_sf(data=southAmerica,
          aes(fill=mobiles_density_FJ5_cat))+
  coord_sf(datum = st_crs(southAmerica)) +
  scale_fill_brewer(direction = 1,palette = 'RdBu') + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing",fill="Mobile Phone Density")

static_choro
```

```{r}
choro_4326 <- st_transform(southAmerica, crs = 4326)
#needed
choro_4326$mobiles_density_FJ5_cat=ordered(choro_4326$mobiles_density_FJ5_cat)
# First, create a color palette for your categorical variable
pal <- colorFactor(palette = "RdBu",
                   domain = choro_4326$mobiles_density_FJ5_cat,
                   ordered = T,
                   reverse = F)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
  addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_density_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1
  ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$mobiles_density_FJ5_cat,
  )
```

```{r}
# Calculate the center of Africa for the home button
southAm_center <- st_bbox(choro_4326) %>% 
  as.vector() %>% 
  {c(mean(c(.[1], .[3])), mean(c(.[2], .[4])))}  # Calculate center coordinates


interactive_choro=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
  addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_density_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1,
    label = lapply(
      paste("<strong>", choro_4326$Country, "</strong><br>",
            "Density: ", round(choro_4326$mobiles_density, 4)),
      htmltools::HTML
    )
  ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$population_density_FJ5_cat,
    opacity = 0.7,
    title = "Mobile Phone Density",
    position = "bottomright"
  )%>%
  addEasyButton(
    easyButton(
      icon = "fa-home", 
      title = "Reset to South America View",
      onClick = JS(sprintf("function(btn, map){ map.setView([%f, %f], 3); }", 
                           southAm_center[2], southAm_center[1]))
    )
  )
interactive_choro
```

```{r}
saveRDS(interactive_ddm, file = "interactive_ddm.rds")
saveRDS(interactive_psm, file = "interactive_psm.rds")
saveRDS(interactive_choro, file = "interactive_choro.rds")
```

